include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Ignora avisos de depreciação e lints de estilo que não quebram o código
    deprecated_member_use: ignore
    unused_import: ignore
    dead_code: ignore
    avoid_print: ignore
    use_build_context_synchronously: ignore
    curly_braces_in_flow_control_structures: ignore
    unused_element: ignore
    dead_null_aware_expression: ignore